### PR TITLE
Refactored script to use less dependencies. Added requirements.txt

### PR DESCRIPTION
**Pull request by ESapenaVentura**
- Refactored "get_dummy_fastq.py" to use less dependencies and some other linting changes (not finished in that regard, though)
- Added empty "requirements.txt" to be filled with needed dependencies in the future.

### CODE REVIEW

**Comment by mshadbolt** [comment]
I removed the input flags from the parser because this makes this argument 'optional' whereas I think it is better to have the input fastq list as a required positional argument. Made a few changes to help text.

**Comment by mshadbolt** [comment]
Is the requirements file supposed to be empty?

**Comment by ESapenaVentura** [comment]
@mshadbolt the requirements.txt needs to be filled with the dependencies, I created it while there were still but I deleted both pandas and biopython from the script so it isn't needed.

I just left it there for people to fill it when creating new scripts with dependencies, but it's not necessary. We can delete until needed!

**Comment by ESapenaVentura** [comment]
Actually, the other script in the repo has 4 dependencies so I might fill it.

**Comment by mshadbolt** [comment]
ok cool so we treat it as a requirements file for any script that gets added to this `src` file, that sounds reasonable

**Comment by ESapenaVentura** [comment]
@ami-day could you review and agree/disagree with the changes? Thanks!

**Pull request merged**
