### PR TITLE
Update move data script: make database choice optional

### PR DESCRIPTION
**Pull request by ami-day**
Added choice to request fastq retrieval via ena as opposed to a default, sra.

### CODE REVIEW

**Comment by ami-day** [comment]
Small change: should be a very short review.

**Comment by ESapenaVentura** [comment]
LGTM, but I have a question: why would you want to specify one over the other? is there any underlying issue that we would need to tackle instead of patching?

**Comment by ami-day** [comment]
> LGTM, but I have a question: why would you want to specify one over the other? is there any underlying issue that we would need to tackle instead of patching?

Because I had curated the fastq file names with "SRR" and when transferring to an upload area from SRA they had different names. Also because sometimes they are available as fastq in ENA, but not SRA. Also because some study accessions don't seem to be recognised e.g. if they start with "ERP" or "PRJ". Not sure what you mean by patching?

**Comment by ESapenaVentura** [comment]
Hi @ami-day , next time please wait for an answer before merging (Also, when merging please delete branches)

I do believe that getting the files with their original filenames provides more value, but I guess that is up for discussion (Although filename correction was added as a feature request, previously if got from ENA they would have the `SRR...` filename).

About some study accessions not being recognised, this is exactly what I was asking about. Accessions not being recognised is a problem that we should solve, instead of relying in the user inputting a flag when executing the script

Have you had an example where fastq files are available in ENA, not in SRA, and the script could not identify this? If I remember well when I coded this I tried to account for this situation. If that happens, it feels like we should tackle this as well.

Overall I am not very fond of user-relying flags, in this case it feels like a patch rather than a real solution

**Pull request merged**
